### ISSUE TITLE
sproc PlanMiner generates errors ...

### ISSUE THREAD

**Issue by ALZDBA** [channeladvisor/qdstoolbox#23]
DECLARE @PlanMinerID	BIGINT
EXECUTE DBA.[PlanMiner]
 @InstanceIdentifier 			= 	@@SERVERNAME
,@DatabaseName				= 	'mydb'
,@PlanID				= 	31
,@PlanMinerID = @PlanMinerID OUTPUT

**Msg 213, Level 16, State 1, Line 1
Column name or number of supplied values does not match table definition.
Msg 515, Level 16, State 2, Line 1
Cannot insert the value NULL into column 'LogicalOp', table 'DBAQSadmin.DBA.PlanMiner_IndexOperations'; column does not allow nulls. INSERT fails.
The statement has been terminated.**

**Comment by SQLozano** [comment]
That would be an easy fix (just to allow null on that table). Could you attach the execution plan so I can reproduce the issue and make sure there are no other issues with it?

**Comment by SQLozano** [comment]
Got a fix ready: please let me know if that generates any other issues before I can merge it
