### ISSUE TITLE
have query cache clear have options to leave forced plans

### ISSUE THREAD

**Issue by tscstc** [channeladvisor/qdstoolbox#25]
I talked with Erin about this tool after releasing it, and moderated her pre-con session on Query Store during last week's PASS.
That "forced plans not dropped" is a problem with the "default" Query Store cleanup process, and one of the reasons I wrote my own: the QDSCacheCleanup unforces those plans before dropping them.
I haven't implemented "Drop everything but forced plans" yet, but is something I could do: just open an issue in the project and I'll try to get it ready by next week

**Comment by SQLozano** [comment]
(This comes from a discussion in the SQL Community Slack)
